/* Generated By:JavaCC: Do not edit this line. SandwoodParserConstants.java */
package org.sandwood.compiler.srcTools.sourceToSource;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SandwoodParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int ABSTRACT = 12;
  /** RegularExpression Id. */
  int ASSERT = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int BREAK = 15;
  /** RegularExpression Id. */
  int BYTE = 16;
  /** RegularExpression Id. */
  int CASE = 17;
  /** RegularExpression Id. */
  int CATCH = 18;
  /** RegularExpression Id. */
  int CHAR = 19;
  /** RegularExpression Id. */
  int CLASS = 20;
  /** RegularExpression Id. */
  int CONST = 21;
  /** RegularExpression Id. */
  int CONTINUE = 22;
  /** RegularExpression Id. */
  int _DEFAULT = 23;
  /** RegularExpression Id. */
  int DO = 24;
  /** RegularExpression Id. */
  int DOUBLE = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int ENUM = 27;
  /** RegularExpression Id. */
  int EXTENDS = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int FINAL = 30;
  /** RegularExpression Id. */
  int FINALLY = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int FOR = 33;
  /** RegularExpression Id. */
  int GOTO = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int IMPLEMENTS = 36;
  /** RegularExpression Id. */
  int IMPORT = 37;
  /** RegularExpression Id. */
  int INSTANCEOF = 38;
  /** RegularExpression Id. */
  int INT = 39;
  /** RegularExpression Id. */
  int INTERFACE = 40;
  /** RegularExpression Id. */
  int LONG = 41;
  /** RegularExpression Id. */
  int MODEL = 42;
  /** RegularExpression Id. */
  int NATIVE = 43;
  /** RegularExpression Id. */
  int NEW = 44;
  /** RegularExpression Id. */
  int NULL = 45;
  /** RegularExpression Id. */
  int OBSERVE = 46;
  /** RegularExpression Id. */
  int PACKAGE = 47;
  /** RegularExpression Id. */
  int PRIVATE = 48;
  /** RegularExpression Id. */
  int PROTECTED = 49;
  /** RegularExpression Id. */
  int PUBLIC = 50;
  /** RegularExpression Id. */
  int REDUCE = 51;
  /** RegularExpression Id. */
  int RETURN = 52;
  /** RegularExpression Id. */
  int SHORT = 53;
  /** RegularExpression Id. */
  int STATIC = 54;
  /** RegularExpression Id. */
  int STRICTFP = 55;
  /** RegularExpression Id. */
  int SUPER = 56;
  /** RegularExpression Id. */
  int SWITCH = 57;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 58;
  /** RegularExpression Id. */
  int THIS = 59;
  /** RegularExpression Id. */
  int THROW = 60;
  /** RegularExpression Id. */
  int THROWS = 61;
  /** RegularExpression Id. */
  int TRANSIENT = 62;
  /** RegularExpression Id. */
  int TRUE = 63;
  /** RegularExpression Id. */
  int TRY = 64;
  /** RegularExpression Id. */
  int VOID = 65;
  /** RegularExpression Id. */
  int VOLATILE = 66;
  /** RegularExpression Id. */
  int WHILE = 67;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 68;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 69;
  /** RegularExpression Id. */
  int HEX_LITERAL = 70;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 71;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 72;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 73;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 74;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 75;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 76;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 77;
  /** RegularExpression Id. */
  int STRING_LITERAL = 78;
  /** RegularExpression Id. */
  int IDENTIFIER = 79;
  /** RegularExpression Id. */
  int LETTER = 80;
  /** RegularExpression Id. */
  int PART_LETTER = 81;
  /** RegularExpression Id. */
  int LPAREN = 82;
  /** RegularExpression Id. */
  int RPAREN = 83;
  /** RegularExpression Id. */
  int LBRACE = 84;
  /** RegularExpression Id. */
  int RBRACE = 85;
  /** RegularExpression Id. */
  int LBRACKET = 86;
  /** RegularExpression Id. */
  int RBRACKET = 87;
  /** RegularExpression Id. */
  int SEMICOLON = 88;
  /** RegularExpression Id. */
  int COMMA = 89;
  /** RegularExpression Id. */
  int DOT = 90;
  /** RegularExpression Id. */
  int AT = 91;
  /** RegularExpression Id. */
  int ASSIGN = 92;
  /** RegularExpression Id. */
  int LT = 93;
  /** RegularExpression Id. */
  int GT = 94;
  /** RegularExpression Id. */
  int BANG = 95;
  /** RegularExpression Id. */
  int HOOK = 96;
  /** RegularExpression Id. */
  int COLON = 97;
  /** RegularExpression Id. */
  int EQ = 98;
  /** RegularExpression Id. */
  int LE = 99;
  /** RegularExpression Id. */
  int GE = 100;
  /** RegularExpression Id. */
  int NE = 101;
  /** RegularExpression Id. */
  int SC_OR = 102;
  /** RegularExpression Id. */
  int SC_AND = 103;
  /** RegularExpression Id. */
  int INCR = 104;
  /** RegularExpression Id. */
  int DECR = 105;
  /** RegularExpression Id. */
  int PLUS = 106;
  /** RegularExpression Id. */
  int MINUS = 107;
  /** RegularExpression Id. */
  int STAR = 108;
  /** RegularExpression Id. */
  int SLASH = 109;
  /** RegularExpression Id. */
  int REM = 110;
  /** RegularExpression Id. */
  int RANGE = 111;
  /** RegularExpression Id. */
  int ARRAYSET = 112;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 114;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"model\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"observe\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"reduce\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"..\"",
    "\"<~\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
    "\"->\"",
    "\"+=\"",
    "\"-=\"",
  };

}
